### ISSUE TITLE
Erorr build =(

### ISSUE THREAD

**Issue by microwin7** [bs-community/skinview3d#76]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle skinview3d@2.0.0-alpha.10~prebuild: skinview3d@2.0.0-alpha.10
6 silly lifecycle skinview3d@2.0.0-alpha.10~prebuild: no script for prebuild, continuing
7 info lifecycle skinview3d@2.0.0-alpha.10~build: skinview3d@2.0.0-alpha.10
8 verbose lifecycle skinview3d@2.0.0-alpha.10~build: unsafe-perm in lifecycle true
9 verbose lifecycle skinview3d@2.0.0-alpha.10~build: PATH: /usr/share/npm/bin/node-gyp-bin:/mnt/i/GitHub/GAMAI_SERVER/skinview3d/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle skinview3d@2.0.0-alpha.10~build: CWD: /mnt/i/GitHub/GAMAI_SERVER/skinview3d
11 silly lifecycle skinview3d@2.0.0-alpha.10~build: Args: [ '-c', 'npm run build:modules && npm run build:bundles' ]
12 silly lifecycle skinview3d@2.0.0-alpha.10~build: Returned: code: 1  signal: null
13 info lifecycle skinview3d@2.0.0-alpha.10~build: Failed to exec build script
14 verbose stack Error: skinview3d@2.0.0-alpha.10 build: `npm run build:modules && npm run build:bundles`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid skinview3d@2.0.0-alpha.10
16 verbose cwd /mnt/i/GitHub/GAMAI_SERVER/skinview3d
17 error Linux 4.4.0-19041-Microsoft
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error skinview3d@2.0.0-alpha.10 build: `npm run build:modules && npm run build:bundles`
22 error Exit status 1
23 error Failed at the skinview3d@2.0.0-alpha.10 build script 'npm run build:modules && npm run build:bundles'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the skinview3d package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:modules && npm run build:bundles
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs skinview3d
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls skinview3d
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by microwin7** [comment]
and with windows
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle skinview3d@2.0.0-alpha.10~prebuild: skinview3d@2.0.0-alpha.10
6 info lifecycle skinview3d@2.0.0-alpha.10~build: skinview3d@2.0.0-alpha.10
7 verbose lifecycle skinview3d@2.0.0-alpha.10~build: unsafe-perm in lifecycle true
8 verbose lifecycle skinview3d@2.0.0-alpha.10~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;I:\GitHub\GAMAI_SERVER\skinview3d\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_241\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Go\bin;C:\Program Files\WorldPainter;C:\Program Files\PowerShell\7\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Антон\AppData\Local\Microsoft\WindowsApps;C:\Users\Антон\AppData\Local\atom\bin;C:\Users\Антон\AppData\Local\GitHubDesktop\bin;C:\Users\Антон\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1\bin;;C:\Users\Антон\go\bin;C:\Users\Антон\AppData\Roaming\npm
9 verbose lifecycle skinview3d@2.0.0-alpha.10~build: CWD: I:\GitHub\GAMAI_SERVER\skinview3d
10 silly lifecycle skinview3d@2.0.0-alpha.10~build: Args: [ '/d /s /c', 'npm run build:modules && npm run build:bundles' ]
11 silly lifecycle skinview3d@2.0.0-alpha.10~build: Returned: code: 1  signal: null
12 info lifecycle skinview3d@2.0.0-alpha.10~build: Failed to exec build script
13 verbose stack Error: skinview3d@2.0.0-alpha.10 build: `npm run build:modules && npm run build:bundles`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid skinview3d@2.0.0-alpha.10
15 verbose cwd I:\GitHub\GAMAI_SERVER\skinview3d
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.12.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error skinview3d@2.0.0-alpha.10 build: `npm run build:modules && npm run build:bundles`
22 error Exit status 1
23 error Failed at the skinview3d@2.0.0-alpha.10 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by microwin7** [comment]
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:modules' ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'prebuild:modules', 'build:modules', 'postbuild:modules' ]
5 info lifecycle skinview3d@2.0.0-alpha.10~prebuild:modules: skinview3d@2.0.0-alpha.10
6 info lifecycle skinview3d@2.0.0-alpha.10~build:modules: skinview3d@2.0.0-alpha.10
7 verbose lifecycle skinview3d@2.0.0-alpha.10~build:modules: unsafe-perm in lifecycle true
8 verbose lifecycle skinview3d@2.0.0-alpha.10~build:modules: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/i/GitHub/GAMAI_SERVER/skinview3d-2.0.0-alpha.10/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/i/GitHub/GAMAI_SERVER/skinview3d-2.0.0-alpha.10/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle skinview3d@2.0.0-alpha.10~build:modules: CWD: /mnt/i/GitHub/GAMAI_SERVER/skinview3d-2.0.0-alpha.10
10 silly lifecycle skinview3d@2.0.0-alpha.10~build:modules: Args: [ '-c', 'tsc --declaration --sourceMap --outDir libs -p .' ]
11 info lifecycle skinview3d@2.0.0-alpha.10~build:modules: Failed to exec build:modules script
12 verbose stack Error: skinview3d@2.0.0-alpha.10 build:modules: `tsc --declaration --sourceMap --outDir libs -p .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid skinview3d@2.0.0-alpha.10
14 verbose cwd /mnt/i/GitHub/GAMAI_SERVER/skinview3d-2.0.0-alpha.10
15 verbose Linux 4.4.0-19041-Microsoft
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:modules"
17 verbose node v12.18.4
18 verbose npm  v6.14.6
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error skinview3d@2.0.0-alpha.10 build:modules: `tsc --declaration --sourceMap --outDir libs -p .`
23 error spawn ENOENT
24 error Failed at the skinview3d@2.0.0-alpha.10 build:modules script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]```
update nodejs

**Comment by microwin7** [comment]
I am Russian, it was a little hard for me to understand, but I figured it out. You just had to register npm install)

**Comment by yushijinhun** [comment]
Did you run `npm install` before building?
